import { useState } from 'react';
import { useLocation } from 'wouter';

const handleToast = (_msg: string) => {};

export default function BatchReview() {
  const [, navigate] = useLocation();

  return (
    <div className="page active">
      <div className="detail-header"><button className="detail-back" onClick={() => navigate('queue')}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6"/></svg></button><div className="detail-info"><div className="detail-title">— — Photo Review</div><div className="detail-meta">— · 0 photos</div></div><button className="btn btn-s btn-sm" onClick={() => handleToast('Claim created from groups')}>Create Claim from Groups</button></div>
      <div style={{display: 'grid', gridTemplateColumns: '1fr 340px', gap: 20}}>
        <div>
          <div className="pn" style={{marginBottom: 16}}><div style={{padding: '16px 20px', display: 'flex', gap: 12}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="2" style={{flexShrink: 0, marginTop: 2}}><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg><div><div style={{fontSize: 12, fontWeight: 600, marginBottom: 4}}>Dealer's Note</div><div style={{fontSize: 13, color: '#555', lineHeight: '1.5'}}>"Sidewall damage passenger side, roof leak near front vent, slide-out seal torn 18 inches, kitchen cabinet hinge broken."</div></div></div></div>
          <div style={{background: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: 8, padding: '14px 20px', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 12}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2"><path d="M12 2a7 7 0 017 7c0 2.38-1.19 4.47-3 5.74V17a2 2 0 01-2 2h-4a2 2 0 01-2-2v-2.26C6.19 13.47 5 11.38 5 9a7 7 0 017-7z"/></svg><div style={{flex: 1}}><div style={{fontSize: 13, fontWeight: 600, color: '#1e40af'}}>AI detected 4 issues</div><div style={{fontSize: 12, color: '#3b82f6'}}>Suggested groups below. Drag photos between groups.</div></div><button className="btn btn-o btn-sm" style={{borderColor: '#93c5fd', color: '#2563eb'}} onClick={() => handleToast('AI suggestions applied')}>Apply Suggestions</button></div>
          <div className="pn"><div className="pn-h"><span className="pn-t">All Photos (24)</span><span style={{fontSize: 12, color: '#888'}}>Click to assign</span></div>
            <div style={{padding: '16px 20px', display: 'grid', gridTemplateColumns: 'repeat(8,1fr)', gap: 6}}>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', position: 'relative', cursor: 'pointer'}}><span style={{position: 'absolute', top: 3, left: 3, background: '#ef4444', color: 'white', fontSize: 8, padding: '1px 4px', borderRadius: 3}}>1</span>001</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', position: 'relative', cursor: 'pointer'}}><span style={{position: 'absolute', top: 3, left: 3, background: '#ef4444', color: 'white', fontSize: 8, padding: '1px 4px', borderRadius: 3}}>1</span>002</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', position: 'relative', cursor: 'pointer'}}><span style={{position: 'absolute', top: 3, left: 3, background: '#3b82f6', color: 'white', fontSize: 8, padding: '1px 4px', borderRadius: 3}}>2</span>003</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', position: 'relative', cursor: 'pointer'}}><span style={{position: 'absolute', top: 3, left: 3, background: '#22c55e', color: 'white', fontSize: 8, padding: '1px 4px', borderRadius: 3}}>3</span>004</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', position: 'relative', cursor: 'pointer'}}><span style={{position: 'absolute', top: 3, left: 3, background: '#a855f7', color: 'white', fontSize: 8, padding: '1px 4px', borderRadius: 3}}>4</span>005</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', cursor: 'pointer'}}>006</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', cursor: 'pointer'}}>...</div>
              <div style={{aspectRatio: 1, background: '#e8e8e8', borderRadius: 6, fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#888', cursor: 'pointer'}}>024</div>
            </div></div>
        </div>
        <div>
          <div style={{fontSize: 14, fontWeight: 600, marginBottom: 12}}>Issue Groups → FRC Lines</div>
          <div style={{background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8, marginBottom: 12, borderLeft: '3px solid #ef4444', padding: '14px 16px'}}><div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8}}><span style={{background: '#ef4444', color: 'white', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4}}>1</span><span style={{fontSize: 13, fontWeight: 600}}>Delamination, Sidewall</span></div><select style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', background: '#fafafa', marginBottom: 6}}><option>JC-WAR-1042 (2.5 hrs)</option></select><textarea style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', minHeight: 36, resize: 'vertical'}}>Passenger side delamination, 2x3 ft</textarea></div>
          <div style={{background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8, marginBottom: 12, borderLeft: '3px solid #3b82f6', padding: '14px 16px'}}><div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8}}><span style={{background: '#3b82f6', color: 'white', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4}}>2</span><span style={{fontSize: 13, fontWeight: 600}}>Water Leak, Roof Vent</span></div><select style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', background: '#fafafa', marginBottom: 6}}><option>JC-WAR-2018 (1.5 hrs)</option></select><textarea style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', minHeight: 36, resize: 'vertical'}}>Active intrusion front roof vent</textarea></div>
          <div style={{background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8, marginBottom: 12, borderLeft: '3px solid #22c55e', padding: '14px 16px'}}><div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8}}><span style={{background: '#22c55e', color: 'white', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4}}>3</span><span style={{fontSize: 13, fontWeight: 600}}>Slide-Out Seal</span></div><select style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', background: '#fafafa'}}><option>JC-WAR-3055 (1.0 hrs)</option></select></div>
          <div style={{background: '#fff', border: '1px solid #e5e7eb', borderRadius: 8, marginBottom: 12, borderLeft: '3px solid #a855f7', padding: '14px 16px'}}><div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8}}><span style={{background: '#a855f7', color: 'white', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4}}>4</span><span style={{fontSize: 13, fontWeight: 600}}>Cabinet Hinge</span></div><select style={{width: '100%', padding: '7px 10px', border: '1px solid #e0e0e0', borderRadius: 6, fontSize: 12, fontFamily: 'inherit', background: '#fafafa'}}><option>JC-WAR-4012 (0.5 hrs)</option></select></div>
          <button style={{width: '100%', padding: 12, border: '2px dashed #d0d0d0', borderRadius: 8, background: 'none', color: '#888', fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', marginBottom: 16}} onClick={() => handleToast('Issue group added')}>+ Add Issue Group</button>
          <div style={{background: 'var(--brand)', borderRadius: 8, padding: 16, color: 'white'}}><div style={{fontSize: 13, fontWeight: 600, marginBottom: 8}}>Claim Summary</div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: 12, opacity: '0.7', marginBottom: 4}}><span>FRC Lines</span><span>4</span></div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: 12, opacity: '0.7', marginBottom: 4}}><span>Total Hours</span><span>5.5</span></div><div style={{borderTop: '1px solid rgba(255,255,255,0.15)', marginTop: 8, paddingTop: 8, display: 'flex', justifyContent: 'space-between', fontSize: 14, fontWeight: 600}}><span>Est. Value</span><span>$1,240</span></div></div>
        </div>
      </div>
    </div>
  );
}
