import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { apiFetch } from '@/lib/api';

// Auto-generated by scripts/update-changelog.ts on each build.
// Imported synchronously — falls back to empty array if file is absent or malformed.
import _changelogRaw from '@/data/changelog.json';

type ChangelogEntry = {
  version: string;
  date: string;
  features: string[];
  fixes: string[];
  improvements: string[];
  docs: string[];
  other: string[];
};

const changelogData: ChangelogEntry[] = Array.isArray(_changelogRaw) ? (_changelogRaw as ChangelogEntry[]) : [];

export default function Changelog() {
  const [, navigate] = useLocation();
  const [clTab, setClTab] = useState('cltab-cl-current');
  const [opFeatureRequests, setOpFeatureRequests] = useState<any[]>([]);

  useEffect(() => {
    apiFetch<any>('/api/feature-requests').then(d => setOpFeatureRequests(Array.isArray(d) ? d : [])).catch(() => {});
  }, []);

  // Latest + past entries from auto-generated changelog.json
  const latestEntry: ChangelogEntry | null = changelogData.length > 0 ? changelogData[0] : null;
  const pastEntries: ChangelogEntry[] = changelogData.length > 1 ? changelogData.slice(1) : [];

  const dot = (color: string) => (
    <span style={{display: 'inline-block', width: 6, height: 6, borderRadius: '50%', background: color, marginRight: 8}}></span>
  );

  return (
    <div className="page active">
      <div className="tabs"><div className={`tab ${clTab === 'cltab-cl-current' ? 'active' : ''}`} onClick={() => setClTab('cltab-cl-current')}>Current Release</div><div className={`tab ${clTab === 'cltab-cl-past' ? 'active' : ''}`} onClick={() => setClTab('cltab-cl-past')}>Past Updates</div><div className={`tab ${clTab === 'cltab-cl-upcoming' ? 'active' : ''}`} onClick={() => setClTab('cltab-cl-upcoming')}>Upcoming</div><div className={`tab ${clTab === 'cltab-cl-requests' ? 'active' : ''}`} onClick={() => setClTab('cltab-cl-requests')}>Feature Requests</div></div>

      <div style={{display: clTab === 'cltab-cl-current' ? 'block' : 'none'}} className="pn">
        <div style={{padding: '24px 20px', borderBottom: '1px solid #f0f0f0'}}>
          <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start'}}>
            <div>
              <div style={{fontSize: 24, fontWeight: 700, color: 'var(--brand)', marginBottom: 4}}>
                {latestEntry ? `v${latestEntry.version}` : 'v2.1.0'}
              </div>
              <div style={{fontSize: 14, color: '#888'}}>
                {latestEntry ? `Generated ${latestEntry.date}` : 'Released May 23, 2026'}
              </div>
            </div>
            <span className="bg active" style={{fontSize: 13, padding: '6px 16px'}}>Latest</span>
          </div>
          <div style={{fontSize: 14, color: '#333', marginTop: 12, lineHeight: '1.6'}}>Complete 13-portal architecture with full route registration, 157 page components, and a production-ready data import system with CSV templates, API endpoints, and custom field passthrough.</div>
        </div>

        {/* Auto-generated summary from git log (shown only when changelog.json exists and has entries) */}
        {latestEntry && (latestEntry.features.length > 0 || latestEntry.fixes.length > 0 || latestEntry.improvements.length > 0) && (
          <div style={{padding: '16px 20px', background: '#f8fafc', borderBottom: '1px solid #f0f0f0'}}>
            <div style={{fontSize: 12, fontWeight: 600, color: '#64748b', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10}}>
              Auto-generated from git log
            </div>
            {latestEntry.features.length > 0 && (
              <div style={{marginBottom: 8}}>
                <span style={{fontSize: 11, fontWeight: 700, color: '#22c55e', marginRight: 8}}>FEATURES</span>
                {latestEntry.features.slice(0, 3).map((f, i) => (
                  <div key={i} style={{fontSize: 12, color: '#475569', lineHeight: 1.8, paddingLeft: 12}}>{dot('#22c55e')}{f}</div>
                ))}
                {latestEntry.features.length > 3 && <div style={{fontSize: 11, color: '#94a3b8', paddingLeft: 12}}>+{latestEntry.features.length - 3} more</div>}
              </div>
            )}
            {latestEntry.fixes.length > 0 && (
              <div style={{marginBottom: 8}}>
                <span style={{fontSize: 11, fontWeight: 700, color: '#3b82f6', marginRight: 8}}>FIXES</span>
                {latestEntry.fixes.slice(0, 3).map((f, i) => (
                  <div key={i} style={{fontSize: 12, color: '#475569', lineHeight: 1.8, paddingLeft: 12}}>{dot('#3b82f6')}{f}</div>
                ))}
              </div>
            )}
            {latestEntry.improvements.length > 0 && (
              <div>
                <span style={{fontSize: 11, fontWeight: 700, color: '#f59e0b', marginRight: 8}}>IMPROVEMENTS</span>
                {latestEntry.improvements.slice(0, 3).map((f, i) => (
                  <div key={i} style={{fontSize: 12, color: '#475569', lineHeight: 1.8, paddingLeft: 12}}>{dot('#f59e0b')}{f}</div>
                ))}
              </div>
            )}
          </div>
        )}
        <div style={{padding: 20}}>
          <div style={{marginBottom: 24}}>
            <div style={{fontSize: 13, fontWeight: 600, color: '#22c55e', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12}}>New Features</div>
            <div style={{fontSize: 13, color: '#333', lineHeight: 2}}>
              <div>{dot('#22c55e')}<strong>13-Portal Architecture</strong> — Dedicated layout + page components for every role: Operator Admin, Operator Staff, Dealer Owner, Dealer Staff, Client, Service Manager, Shop Manager, Parts Manager, Financial Manager, Shop Technician, On-Site Technician, Public Bidder, Consignor</div>
              <div>{dot('#22c55e')}<strong>215 Routes Live</strong> — Full route registration across all 13 portals via centralized PortalRoutes.tsx</div>
              <div>{dot('#22c55e')}<strong>157 Page Components</strong> — All portal pages built with UI content, tables, forms, and interactions</div>
              <div>{dot('#22c55e')}<strong>DevAccess Portal Selector</strong> — Role-based entry point listing all 13 portal types for development and QA access</div>
              <div>{dot('#22c55e')}<strong>Data Import System</strong> — 4-step wizard (entity select → file upload → column mapping → review) supporting Units, Customers, Claims, Warranty Plans, and F&I Deals</div>
              <div>{dot('#22c55e')}<strong>Downloadable CSV Templates</strong> — Client-side template generation with correct headers and sample rows for all 5 entity types</div>
              <div>{dot('#22c55e')}<strong>Custom Data Passthrough</strong> — Unmapped import columns stored as <code>custom_data</code> JSON and surfaced on Unit Detail and Claim Detail pages</div>
            </div>
          </div>
          <div style={{marginBottom: 24}}>
            <div style={{fontSize: 13, fontWeight: 600, color: '#3b82f6', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12}}>API & Backend</div>
            <div style={{fontSize: 13, color: '#333', lineHeight: 2}}>
              <div>{dot('#3b82f6')}5 import endpoints: <code>GET/POST /api/import/templates</code>, <code>DELETE /api/import/templates/:id</code>, <code>POST /api/import/preview</code>, <code>POST /api/import/run</code>, <code>GET /api/import/history</code></div>
              <div>{dot('#3b82f6')}File parsing via multer (memory storage) + SheetJS (xlsx) — supports CSV and XLSX uploads</div>
              <div>{dot('#3b82f6')}Fuzzy header detection maps common column name variants to standard fields automatically</div>
              <div>{dot('#3b82f6')}Atomic import transactions with per-row error capture and partial-success support</div>
              <div>{dot('#3b82f6')}Import history logged with row counts, error details, status, and timestamps</div>
            </div>
          </div>
          <div style={{marginBottom: 24}}>
            <div style={{fontSize: 13, fontWeight: 600, color: '#8b5cf6', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12}}>Schema Changes</div>
            <div style={{fontSize: 13, color: '#333', lineHeight: 2}}>
              <div>{dot('#8b5cf6')}<code>custom_data jsonb</code> column added to: <code>units</code>, <code>claims</code>, <code>fi_deals</code>, <code>warranty_plans</code>, <code>users</code></div>
              <div>{dot('#8b5cf6')}New <code>import_templates</code> table — reusable column mapping configurations per dealer and entity type</div>
              <div>{dot('#8b5cf6')}New <code>import_history</code> table — audit trail for every import run with row-level error tracking</div>
            </div>
          </div>
          <div>
            <div style={{fontSize: 13, fontWeight: 600, color: '#f59e0b', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12}}>Improvements</div>
            <div style={{fontSize: 13, color: '#333', lineHeight: 2}}>
              <div>{dot('#f59e0b')}Import Data nav link added to Operator Admin, Dealer Owner, and Dealer Staff sidebars</div>
              <div>{dot('#f59e0b')}VIN dependency warning shown on import template banner for Claims, Warranty, and F&I entity types</div>
              <div>{dot('#f59e0b')}Dynamic template banner headings reflect the selected entity type in real time</div>
            </div>
          </div>
        </div>
      </div>

      <div style={{display: clTab === 'cltab-cl-past' ? 'block' : 'none'}} className="pn">
        <div style={{padding: 20}}>

          {/* Auto-generated past entries from git log */}
          {pastEntries.map(e => (
            <div key={e.version} style={{borderLeft: '3px solid #6366f1', paddingLeft: 20, marginBottom: 32}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}>
                <div style={{fontSize: 18, fontWeight: 700}}>v{e.version}</div>
                <span style={{fontSize: 12, color: '#888'}}>{e.date}</span>
              </div>
              <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
                {e.features.map((f, i) => <div key={i}>{dot('#22c55e')}{f}</div>)}
                {e.fixes.map((f, i) => <div key={i}>{dot('#3b82f6')}{f}</div>)}
                {e.improvements.map((f, i) => <div key={i}>{dot('#f59e0b')}{f}</div>)}
              </div>
            </div>
          ))}

          <div style={{borderLeft: '3px solid #e5e7eb', paddingLeft: 20, marginBottom: 32}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700}}>v2.0.0</div><span style={{fontSize: 12, color: '#888'}}>March 17, 2026</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>GEN2 platform — three-portal system (Operator, Dealer, Customer), dark mode, EN/FR bilingual</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
              <div>• Three-Portal System — Operator (36 pages), Dealer (25 pages), Customer (14 pages)</div>
              <div>• Service Marketplace — Financing, F&I, Warranty Plans, Parts & Accessories</div>
              <div>• Wave-style Invoice Builder with line items, part search, and tax calculation</div>
              <div>• RBAC — 4 roles: Operator Admin, Operator Staff, Dealer Owner, Dealer Staff</div>
              <div>• Dark Mode + EN/FR persisted via localStorage across all portals</div>
              <div>• Changelog system with current, past, upcoming, and feature request tabs</div>
            </div>
          </div>
          <div style={{borderLeft: '3px solid #e5e7eb', paddingLeft: 20, marginBottom: 32}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700}}>v1.0.0</div><span style={{fontSize: 12, color: '#888'}}>November 2025</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>Original dealersuite360.com portal — single-portal claims tracking system</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
              <div>• Basic claims tracking portal (operator only)</div>
              <div>• Bilingual website (EN/FR) with marketing pages</div>
              <div>• Pattern-matching chatbot (no AI)</div>
              <div>• In-memory data storage (no persistence)</div>
            </div>
          </div>
          <div style={{borderLeft: '3px solid #e5e7eb', paddingLeft: 20}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700}}>v0.1.0 — Beta</div><span style={{fontSize: 12, color: '#888'}}>October 2025</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>Initial build on Replit — marketing website only</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}><div>• Marketing website with service pages</div><div>• Contact form</div><div>• React + Express + TypeScript foundation</div></div>
          </div>
        </div>
      </div>

      <div style={{display: clTab === 'cltab-cl-upcoming' ? 'block' : 'none'}} className="pn">
        <div style={{padding: 20}}>
          <div style={{marginBottom: 28}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700, color: 'var(--brand)'}}>v2.2.0 — Phase 2</div><span className="bg pending" style={{padding: '4px 12px'}}>In Development</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>Authentication & Payments — Target: June 2026</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
              <div>• JWT authentication with refresh tokens and session management</div>
              <div>• RBAC middleware enforcement on all API routes</div>
              <div>• Stripe integration — subscriptions, one-time invoices, pre-funded wallet</div>
              <div>• Interac e-Transfer reconciliation (Canadian market)</div>
              <div>• Real-time WebSocket messaging between operators and dealers</div>
              <div>• Email notifications via SendGrid/SES</div>
            </div>
          </div>
          <div style={{marginBottom: 28}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700, color: '#555'}}>v2.3.0 — Phase 3</div><span className="bg draft" style={{padding: '4px 12px'}}>Planned</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>AI Integration & Mobile — Target: Q3 2026</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
              <div>• AI Document Scanner (OCR + field extraction)</div>
              <div>• AI FRC Code Suggestions from claim descriptions and photos</div>
              <div>• Photo Quality Gatekeeper with flagging and recommendations</div>
              <div>• Claim Readiness Score (0–100% confidence before submission)</div>
              <div>• PWA mobile app for dealers and technicians</div>
              <div>• AI F&I Presenter (Tavus/D-ID live video avatar)</div>
            </div>
          </div>
          <div>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8}}><div style={{fontSize: 18, fontWeight: 700, color: '#555'}}>v3.0.0 — Full Launch</div><span className="bg draft" style={{padding: '4px 12px'}}>Planned</span></div>
            <div style={{fontSize: 13, color: '#888', marginBottom: 12}}>Dealer Suite 360 North American Launch — Target: Q4 2026</div>
            <div style={{fontSize: 13, color: '#555', lineHeight: '1.8'}}>
              <div>• dealersuite360.com full public launch (US market)</div>
              <div>• Multi-currency support (CAD / USD)</div>
              <div>• Dealer-to-dealer marketplace and live auctions</div>
              <div>• Consumer direct services (roadside, extended warranty, protection)</div>
              <div>• Advanced analytics and revenue reporting dashboard</div>
              <div>• White-label deployment framework for RVClaims.ca and future markets</div>
            </div>
          </div>
        </div>
      </div>

      <div style={{display: clTab === 'cltab-cl-requests' ? 'block' : 'none'}} className="pn">
        <div style={{padding: '16px 20px', borderBottom: '1px solid #f0f0f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
          <span style={{fontSize: 13, color: '#888'}}>Feature requests from dealers and internal team</span>
          <button className="btn btn-p btn-sm" onClick={() => navigate('add-feature-req')}>+ Add Request</button>
        </div>
        <div className="tw"><table><thead><tr><th>Request</th><th>Requested By</th><th>Priority</th><th>Status</th><th>Target</th></tr></thead><tbody>
          {opFeatureRequests.length === 0
            ? <tr><td colSpan={5} style={{textAlign:'center',color:'#888',padding:20}}>No feature requests yet</td></tr>
            : opFeatureRequests.map((fr: any) => {
              const priColor = fr.priority === 'high' ? '#dc2626' : fr.priority === 'low' ? '#22c55e' : '#d97706';
              return (
                <tr key={fr.id}>
                  <td style={{fontWeight: 500}}>{fr.title}</td>
                  <td>{fr.requestedBy || 'Internal'}</td>
                  <td><span style={{color: priColor, fontWeight: 600, fontSize: 12}}>{fr.priority ? fr.priority.charAt(0).toUpperCase() + fr.priority.slice(1) : 'Medium'}</span></td>
                  <td><span className={`bg ${fr.status === 'planned' ? 'submitted' : 'draft'}`}>{fr.status === 'planned' ? 'Planned' : 'Backlog'}</span></td>
                  <td>{fr.targetVersion || '—'}</td>
                </tr>
              );
            })
          }
        </tbody></table></div>
      </div>
    </div>
  );
}
