import { useLocation } from 'wouter';

export default function ServiceMarketplace() {
  const [, navigate] = useLocation();

  const toggle = (e: React.MouseEvent<HTMLDivElement>) => {
    (e.currentTarget as HTMLElement).classList.toggle('on');
  };

  return (
    <div className="page active">
      <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20}}>
        <div>
          <div style={{fontSize: 16, fontWeight: 700, marginBottom: 4}}>Service Modules</div>
          <div style={{fontSize: 13, color: '#888'}}>Manage platform services. Toggle modules on/off and set pricing per service.</div>
        </div>
      </div>
      <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16}}>
        <div className="svc-card"><div className="svc-icon" style={{background: '#eff6ff', color: '#3b82f6'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/></svg></div><div className="svc-body"><div className="svc-title">Claims Processing</div><div className="svc-desc">DAF, PDI, Warranty, Extended, Insurance</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>Included</span><span className="cid" onClick={() => navigate('queue')} style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card"><div className="svc-icon" style={{background: '#faf5ff', color: '#a855f7'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg></div><div className="svc-body"><div className="svc-title">Financing Services</div><div className="svc-desc">Lender applications, rate shopping, approval tracking</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>$199/mo</span><span className="cid" onClick={() => navigate('svc-financing')} style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card"><div className="svc-icon" style={{background: '#fffbeb', color: '#f59e0b'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 7V5a4 4 0 00-8 0v2"/></svg></div><div className="svc-body"><div className="svc-title">F&I Services</div><div className="svc-desc">Product recommendations, compliance, margin optimization</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>$299/mo</span><span className="cid" onClick={() => navigate('svc-fi')} style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card"><div className="svc-icon" style={{background: '#f0fdf4', color: '#22c55e'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 12l2 2 4-4"/></svg></div><div className="svc-body"><div className="svc-title">Warranty & Extended Plans</div><div className="svc-desc">Plan management, renewals, direct sales to customers</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>Included + commissions</span><span className="cid" onClick={() => navigate('svc-warranty')} style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card"><div className="svc-icon" style={{background: '#fef3c7', color: '#d97706'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 7h-9"/><path d="M14 17H5"/><circle cx="17" cy="17" r="3"/><circle cx="7" cy="7" r="3"/></svg></div><div className="svc-body"><div className="svc-title">Parts & Accessories</div><div className="svc-desc">Sourcing, quoting, delivery tracking. Shop coming soon.</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>$149/mo</span><span className="cid" onClick={() => navigate('svc-parts')} style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card" style={{opacity: '0.5'}}><div className="svc-icon" style={{background: '#fef2f2', color: '#ef4444'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/></svg></div><div className="svc-body"><div className="svc-title">Digital Marketing</div><div className="svc-desc">SEO, PPC, social, lead generation</div><div className="svc-meta"><span className="bg pending">Coming Q3</span><span style={{color: '#555'}}>Custom</span></div></div><div className="toggle"></div></div>
        <div className="svc-card" onClick={() => navigate('mkt-listings')} style={{cursor: 'pointer'}}><div className="svc-icon" style={{background: '#e0e7ff', color: '#4f46e5'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="12" y1="17" x2="12" y2="21"/></svg></div><div className="svc-body"><div className="svc-title">Dealer Marketplace</div><div className="svc-desc">Dealer-to-dealer listings and network</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>Commission</span><span className="cid" style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card" onClick={() => navigate('mkt-auctions')} style={{cursor: 'pointer'}}><div className="svc-icon" style={{background: '#dcfce7', color: '#16a34a'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 20V10"/><path d="M18 20V4"/><path d="M6 20v-4"/></svg></div><div className="svc-body"><div className="svc-title">Live Auctions</div><div className="svc-desc">Real-time wholesale bidding</div><div className="svc-meta"><span className="bg active">Live</span><span style={{color: '#555'}}>Transaction fees</span><span className="cid" style={{marginLeft: 'auto', fontSize: 11}}>Open →</span></div></div><div className="toggle on" onClick={toggle}></div></div>
        <div className="svc-card" style={{opacity: '0.5'}}><div className="svc-icon" style={{background: '#fef2f2', color: '#dc2626'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07"/></svg></div><div className="svc-body"><div className="svc-title">Roadside Assistance (B2C)</div><div className="svc-desc">24/7 emergency support direct to RV owners</div><div className="svc-meta"><span className="bg pending">Coming Q4</span><span style={{color: '#555'}}>Per-subscriber</span></div></div><div className="toggle"></div></div>
        <div className="svc-card" style={{opacity: '0.5'}}><div className="svc-icon" style={{background: '#f0f4f8', color: '#64748b'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z"/></svg></div><div className="svc-body"><div className="svc-title">Service Dept Support</div><div className="svc-desc">Mobile service, scheduling, technician training</div><div className="svc-meta"><span className="bg pending">Coming Q3</span><span style={{color: '#555'}}>Custom</span></div></div><div className="toggle"></div></div>
      </div>
    </div>
  );
}
