// server/db/seedModules.ts — Seed the 12 DS360 service modules
// Run via: npx tsx server/seed.ts (called from main seed)

import { db } from "../db";
import { serviceModules } from "@shared/schema";
import { eq } from "drizzle-orm";

const MODULES = [
  {
    name: "Claims Processing",
    slug: "claims-processing",
    tagline: "Streamline your warranty claims from inspection to payment",
    description: [
      "The backbone of your dealership operations, DS360 Claims Processing gives your team a complete end-to-end warranty claims management system purpose-built for RV dealerships. From the moment a unit arrives on your lot to final manufacturer payment, every step is tracked, documented, and optimized for maximum approval rates.",
      "Our expert operator team reviews every claim before submission, catching errors and optimizing FRC code selection based on years of manufacturer-specific experience. AI photo quality analysis flags issues before they become denial reasons.",
      "With DS360, dealerships typically see 23% fewer denials and 18% faster payment cycles within the first 90 days.",
    ].join("\n\n"),
    features: [
      "Full claims lifecycle management",
      "FRC code library by manufacturer",
      "Batch photo upload with Push to Claim",
      "Operator processing queue with assign and review",
      "Per-line approve and deny with denial reasons",
      "Manufacturer portal submission tracking",
      "Preauth and claim number tracking",
      "Claim-to-invoice workflow",
    ],
    icon: "FileText",
    category: "Claims",
    monthlyPrice: "0",
    isBase: true,
    sortOrder: 1,
  },
  {
    name: "Extended Warranty",
    slug: "extended-warranty",
    tagline: "Sell and manage extended warranty plans for every unit",
    description: [
      "Extended warranty sales are one of the highest-margin revenue opportunities in RV dealerships. DS360 Extended Warranty gives you a complete platform to create, sell, and manage extended service plans that keep customers protected long after the manufacturer warranty expires.",
      "Build custom warranty tiers across 6 coverage categories, track every active plan with automated renewal alerts, and generate professional warranty certificates your customers can access anytime.",
      "Integration with the claims module means warranty coverage is automatically verified when a claim is filed, reducing manual lookup time and ensuring customers get the service they are entitled to.",
    ].join("\n\n"),
    features: [
      "Custom warranty plan creation",
      "6 coverage categories (Structural, Plumbing, Electrical, HVAC, Appliances, Slide-Outs)",
      "Customer-facing warranty display with days remaining",
      "Automated renewal tracking and alerts",
      "Coverage breakdown per category",
      "Warranty certificate generation",
    ],
    icon: "Shield",
    category: "Finance",
    monthlyPrice: "149",
    isBase: false,
    sortOrder: 2,
  },
  {
    name: "GAP Coverage",
    slug: "gap-coverage",
    tagline: "Protect your customers against depreciation gaps",
    description: [
      "RVs depreciate rapidly, and a total loss without GAP coverage can leave your customers underwater on their loan. DS360 GAP Coverage lets you offer, enroll, and manage GAP insurance products directly from your dealership portal.",
      "Track every active GAP policy, process GAP claims when needed, and integrate seamlessly with your F&I workflow so no deal leaves your lot without the right protection discussion.",
      "Policy documents are stored digitally and customers can access them through the Customer Portal module, reducing your administrative burden while improving the customer experience.",
    ].join("\n\n"),
    features: [
      "GAP product catalog management",
      "Customer enrollment and tracking",
      "Integration with F&I deal workflow",
      "Claims processing for GAP coverage",
      "Policy document management",
    ],
    icon: "Umbrella",
    category: "Finance",
    monthlyPrice: "99",
    isBase: false,
    sortOrder: 3,
  },
  {
    name: "Roadside Assistance",
    slug: "roadside-assistance",
    tagline: "24/7 roadside support for your customers wherever they travel",
    description: [
      "When your customers are on the road, they need to know help is just a call away. DS360 Roadside Assistance lets you offer a branded roadside service program that your customers can activate from their phone, with real-time dispatch and status tracking.",
      "Manage your service provider network, verify coverage by VIN, and handle dispatch all from the DS360 platform. Whether a customer needs a tow, a tire change, or emergency fuel, your team has the tools to coordinate a fast response.",
      "Adding roadside assistance to your customer offering increases perceived value at purchase and creates a recurring revenue stream that extends well beyond the initial sale.",
    ].join("\n\n"),
    features: [
      "Service request management and dispatch",
      "Customer mobile access for roadside calls",
      "Coverage verification by VIN",
      "Service provider network",
      "Real-time status tracking",
    ],
    icon: "Truck",
    category: "Support",
    monthlyPrice: "79",
    isBase: false,
    sortOrder: 4,
  },
  {
    name: "F&I Services",
    slug: "fi-services",
    tagline: "Maximize every deal with AI-powered F&I presentations",
    description: [
      "Finance and Insurance products represent some of the highest-margin revenue in any dealership. DS360 F&I Services gives your team a complete product catalog, deal tracking system, and an AI-powered video presenter that delivers personalized F&I presentations to every customer — even remotely.",
      "The AI F&I Presenter creates custom video sessions where customers can review products at their own pace, ask questions, and accept coverage options digitally. Real-time analytics show you exactly which products are being accepted and where customers drop off.",
      "No more rushed F&I conversations at the signing table. DS360 F&I lets you start the conversation early, track every product, and maximize per-deal revenue with data-driven recommendations.",
    ].join("\n\n"),
    features: [
      "Complete F&I product catalog",
      "AI-powered video F&I Presenter",
      "Customer self-service acceptance portal",
      "Deal tracking and commission reporting",
      "Real-time acceptance analytics",
      "Automated product recommendations",
    ],
    icon: "TrendingUp",
    category: "Finance",
    monthlyPrice: "299",
    isBase: false,
    sortOrder: 5,
  },
  {
    name: "Financing Services",
    slug: "financing-services",
    tagline: "Connect with lender partners for seamless customer financing",
    description: [
      "Getting customers financed quickly and at the best rate is critical to closing deals. DS360 Financing Services connects your dealership with a network of lender partners and gives your team the tools to submit applications, track approvals, and compare rates all in one place.",
      "Digital application submission eliminates paperwork and speeds up the approval process. Automated status notifications keep your team and your customers informed at every stage, from application to funding.",
      "Funded deal reporting gives you a clear view of your financing volume, lender performance, and revenue contribution — the data you need to optimize your lending relationships over time.",
    ].join("\n\n"),
    features: [
      "Multi-lender partner management",
      "Digital application submission",
      "Automated approval tracking",
      "Rate comparison tools",
      "Application status notifications",
      "Funded deal reporting",
    ],
    icon: "CreditCard",
    category: "Finance",
    monthlyPrice: "199",
    isBase: false,
    sortOrder: 6,
  },
  {
    name: "Parts & Accessories",
    slug: "parts-accessories",
    tagline: "Track every part from order to installation",
    description: [
      "Parts and accessories management is one of the most operationally complex areas of any dealership. DS360 Parts & Accessories gives your team a complete system for ordering, receiving, and tracking parts from your supplier network through to installation.",
      "Create purchase orders, track deliveries, manage your parts inventory, and link every parts order directly to the associated claim line. Technicians can request parts from the field, and your parts department can manage fulfillment without losing track of anything.",
      "Claim-linked parts ordering ensures that warranty parts are properly documented and submitted for reimbursement, recovering revenue that often slips through the cracks in manual systems.",
    ].join("\n\n"),
    features: [
      "Parts catalog with supplier management",
      "Purchase order creation and tracking",
      "Delivery and receiving workflow",
      "Technician parts request system",
      "Inventory management",
      "Claim-linked parts ordering",
    ],
    icon: "Package",
    category: "Operations",
    monthlyPrice: "129",
    isBase: false,
    sortOrder: 7,
  },
  {
    name: "TechFlow On-Site Repairs",
    slug: "techflow",
    tagline: "Dispatch technicians and manage service in the field",
    description: [
      "When service happens in the field, you need your team connected. TechFlow gives your dispatch team, service advisors, and technicians a shared platform for work order management, scheduling, and real-time field updates — whether the job is on your lot or at a customer site.",
      "Technicians clock in and out on mobile, capture before-and-after photos, request parts from the field, and update job status in real time. Service advisors see the full picture from their desktop, and nothing falls through the cracks between the shop and the office.",
      "TechFlow integrates directly with Claims, so every service job is properly documented for warranty submission. Parts requests flow directly to your Parts & Accessories module, keeping your whole operation connected.",
    ].join("\n\n"),
    features: [
      "Work order creation and management",
      "Technician assignment and dispatch board",
      "Service appointment scheduling",
      "Mobile time tracking and clock-in",
      "Before and after repair photos",
      "Parts request from field",
    ],
    icon: "Wrench",
    category: "Operations",
    monthlyPrice: "179",
    isBase: false,
    sortOrder: 8,
  },
  {
    name: "Marketing Services",
    slug: "marketing-services",
    tagline: "Launch targeted campaigns to grow your customer base",
    description: [
      "Growing your dealership requires consistent, targeted outreach to the right customers at the right time. DS360 Marketing Services gives you a campaign platform built specifically for RV dealerships, with templates, targeting tools, and performance analytics designed for your industry.",
      "Launch email campaigns, capture leads from your website, and segment your customer database to deliver messages that convert. Automated follow-up sequences keep prospects engaged without adding work to your team.",
      "Every campaign is tracked so you know exactly which messages are driving traffic, generating leads, and contributing to revenue. Stop guessing and start marketing with data.",
    ].join("\n\n"),
    features: [
      "Campaign template library",
      "Custom campaign creation",
      "Lead capture and tracking",
      "Performance analytics",
      "Customer segmentation",
      "Automated follow-up sequences",
    ],
    icon: "Megaphone",
    category: "Sales",
    monthlyPrice: "399",
    isBase: false,
    sortOrder: 9,
  },
  {
    name: "Consignment",
    slug: "consignment",
    tagline: "Manage consigned units and automate seller payouts",
    description: [
      "Consignment programs let you expand your inventory without upfront capital investment. DS360 Consignment gives you everything you need to manage consigned units from agreement signing through to seller payout, with full transparency for both your team and the seller.",
      "Track offers, manage acceptance workflows, and automatically calculate payouts based on your commission and fee structure. A seller communication portal keeps consignors informed without flooding your inbox with status questions.",
      "A public unit showcase lets you market consigned inventory directly to buyers, and commission tracking ensures every deal is properly recorded and reported at month end.",
    ].join("\n\n"),
    features: [
      "Consignment agreement management",
      "Offer tracking and acceptance",
      "Automated payout calculation",
      "Public unit showcase",
      "Seller communication portal",
      "Commission and fee tracking",
    ],
    icon: "RefreshCw",
    category: "Sales",
    monthlyPrice: "149",
    isBase: false,
    sortOrder: 10,
  },
  {
    name: "Marketplace & Auctions",
    slug: "marketplace-auctions",
    tagline: "List units for auction and reach qualified buyers nationwide",
    description: [
      "The DS360 Marketplace & Auctions module connects your inventory with qualified buyers across North America through a dealer-to-dealer auction platform purpose-built for RVs. List units directly from your inventory, set reserve prices, and let the market determine value in real time.",
      "Real-time bidding powered by WebSocket technology means every participant sees live updates as bids come in. Buyer verification and escrow management protect both sides of every transaction, and anonymous bidding keeps the focus on the units, not the personalities.",
      "Whether you are moving aged inventory, sourcing units for your lot, or building a new wholesale channel, DS360 Auctions gives you the reach and the tools to transact with confidence.",
    ].join("\n\n"),
    features: [
      "Unit listing creation from inventory",
      "Real-time bidding with WebSocket",
      "Buyer verification and escrow management",
      "Auction scheduling and lifecycle",
      "Commission tracking at $250 per transaction",
      "Anonymous bidding (buyer identity protected)",
    ],
    icon: "Gavel",
    category: "Sales",
    monthlyPrice: "249",
    perTransactionFee: "250",
    isBase: false,
    sortOrder: 11,
  },
  {
    name: "Payment Plans",
    slug: "service-financing",
    tagline: "Offer flexible payment plans on service repairs",
    description: [
      "When a service repair estimate comes in high, customers often delay or decline needed work. DS360 Payment Plans lets your dealership offer instant financing on service invoices and work orders — keeping repair revenue flowing while giving customers the flexibility they need.",
      "Customers apply directly through the portal with a simple form. The application is forwarded to a third-party financing partner (PayBright, Financeit, or iFinance for Canadian dealers; Affirm, Bread, or Synchrony for US dealers). The partner pays your dealership upfront — the customer repays in monthly installments.",
      "DS360 earns a referral commission on every funded plan. Operators can manually approve, decline, and track all applications across every dealer from the operator admin panel.",
    ].join("\n\n"),
    features: [
      "One-click payment plan offer from invoice or work order",
      "Canadian and US financing partner network",
      "Customer application form with credit consent",
      "Operator manual approval workflow",
      "Dealer view with all application statuses",
      "Customer portal view with active plan details",
      "Country-aware currency (CAD / USD)",
      "Referral commission tracking",
    ],
    icon: "CreditCard",
    category: "Finance",
    monthlyPrice: "49",
    isBase: false,
    sortOrder: 13,
  },
  {
    name: "Service Reminders",
    slug: "service_reminders",
    tagline: "Automated service reminders for every customer",
    description: [
      "Keep your customers engaged year-round with automated service reminders sent under your dealership brand. Configure templates for seasonal prep, warranty expiry alerts, annual service intervals, and custom campaigns.",
      "Customers receive reminders through in-app push notifications, email, and SMS. They control exactly which channels they receive on and can opt out at any time.",
      "Dealers configure templates with variable substitution (customer name, unit details, warranty dates), set trigger rules, and track delivery rates and opt-out stats from a single dashboard.",
    ].join("\n\n"),
    features: [
      "6 template types: winterization, de-winterization, spring prep, warranty expiry, annual service, custom",
      "Date-based and event-based triggers",
      "Variable substitution: {{customerName}}, {{unitYear}}, {{unitMake}}, {{expiryDate}}",
      "Push (in-app), email, and SMS channels",
      "Customer channel preference management",
      "Master opt-out with legal compliance note",
      "Send history with delivery status tracking",
      "Product promotion add-on within reminders",
    ],
    icon: "Bell",
    category: "Operations",
    monthlyPrice: "39",
    isBase: false,
    sortOrder: 15,
  },
  {
    name: "Customer Loyalty",
    slug: "customer_loyalty",
    tagline: "Branded loyalty rewards program that keeps customers coming back",
    description: [
      "Turn every service visit into a reason for your customers to return. DS360 Customer Loyalty lets you create a fully branded rewards program under your dealership name — with points for service visits, referrals, F&I purchases, and survey completions.",
      "Customers earn points automatically and can redeem them for discounts on service, parts, and accessories directly through their Customer Portal. A transparent points history and progress bar toward the next reward keeps engagement high between visits.",
      "Dealers configure the program name, earning rules, and rewards catalog from their portal. Every referral link is tracked, every redemption is logged, and real-time stats show total members, points issued, and rewards redeemed.",
    ].join("\n\n"),
    features: [
      "Branded program name and earning rules configuration",
      "Points for service visits (per dollar), referrals, F&I purchases, and surveys",
      "Rewards catalog: percentage discount, fixed discount, free service, parts credit, custom",
      "Customer portal loyalty page with balance, history, and redemption",
      "Referral link generator with email invite",
      "Members table with manual credit tool",
      "4-stat program dashboard: members, points issued, points redeemed, rewards redeemed",
      "Operator admin adoption stats across all dealers",
    ],
    icon: "Star",
    category: "Sales",
    monthlyPrice: "49",
    isBase: false,
    sortOrder: 16,
  },
  {
    name: "Smart Upsell",
    slug: "smart_upsell",
    tagline: "AI-powered upsell recommendations for your entire customer portfolio",
    description: [
      "DS360 Smart Upsell continuously analyzes every customer's unit across your portfolio and generates timed upsell recommendations you can review, customize, and send under your own dealership brand.",
      "The AI engine monitors warranty expiry dates, unit age, service gaps, seasonal windows, and F&I coverage gaps — automatically surfacing the right offer to the right customer at the right time.",
      "You control the outreach. DS360 provides the intelligence. Every accepted offer converts to trackable revenue, and your conversion dashboard shows exactly which triggers and products perform best.",
    ].join("\n\n"),
    features: [
      "Automated opportunity scanning across all units",
      "7 trigger types: warranty expiry, unit age, service gap, seasonal, F&I gap, mileage, custom",
      "9 recommended product types with estimated value",
      "Urgency scoring: high, medium, low",
      "Dealer-branded offer messages with variable substitution",
      "Customer in-app offer delivery with accept/decline",
      "Conversion dashboard with per-trigger analytics",
    ],
    icon: "TrendingUp",
    category: "Sales",
    monthlyPrice: "79",
    isBase: false,
    sortOrder: 14,
  },
  {
    name: "AI Support",
    slug: "ai_support",
    tagline: "AI-powered customer support bot with access to their real account data",
    description: [
      "Give every customer a smart support assistant that knows their unit, warranty, and claim history. When a customer asks about their warranty coverage, the bot checks their actual record and gives a specific, personalized answer — not a generic one.",
      "The AI Support bot lives in the Customer Portal as a floating chat bubble, available on every page. It pulls from the customer's real data: their unit VIN, warranty expiry, active claims, support tickets, and dealer-configured knowledge base articles.",
      "Dealer-configured FAQ overrides let you pre-answer your most common questions without any AI cost. Complex issues automatically suggest ticket escalation. All conversations are logged and reviewable from your dealer dashboard.",
    ].join("\n\n"),
    features: [
      "Floating chat widget in Customer Portal",
      "Personalized answers from real customer data",
      "Warranty, claims, and ticket context awareness",
      "FAQ overrides — no AI cost for common questions",
      "Automatic ticket escalation suggestions",
      "Conversation logs with full review capability",
      "Dealer greeting customization",
      "50 messages/day rate limiting per customer",
    ],
    icon: "MessageSquare",
    category: "Support",
    monthlyPrice: "59",
    isBase: false,
    sortOrder: 17,
  },
  {
    name: "Customer Portal",
    slug: "customer-portal",
    tagline: "Give your customers a branded self-service experience",
    description: [
      "Your customers expect a modern digital experience. DS360 Customer Portal gives every customer a branded self-service portal where they can track their claim status, view their warranty coverage, access documents, and contact your team — all without calling or emailing.",
      "White-label with your dealership logo and brand colors, the portal can be deployed on your own custom domain so it feels like a natural extension of your dealership website. Customers can open support tickets, engage in quick chat, and never feel out of the loop on the status of their unit.",
      "Reducing inbound status calls frees up your team for higher-value work, and customers who feel informed and supported are more likely to return for their next purchase.",
    ].join("\n\n"),
    features: [
      "White-label portal with custom domain",
      "Customer claim status tracking",
      "Warranty coverage display",
      "Document access and downloads",
      "Support ticket system",
      "Quick chat with dealership",
      "Branded with your logo and colors",
    ],
    icon: "Users",
    category: "Support",
    monthlyPrice: "99",
    isBase: false,
    sortOrder: 12,
  },
];

export async function seedModules() {
  console.log("  🔧 Seeding service modules...");
  let seeded = 0;
  let skipped = 0;

  for (const mod of MODULES) {
    const [existing] = await db
      .select()
      .from(serviceModules)
      .where(eq(serviceModules.slug, mod.slug))
      .limit(1);

    if (!existing) {
      await db.insert(serviceModules).values({
        name: mod.name,
        slug: mod.slug,
        tagline: mod.tagline,
        description: mod.description,
        features: mod.features,
        icon: mod.icon,
        category: mod.category,
        monthlyPrice: mod.monthlyPrice || "0",
        perTransactionFee: mod.perTransactionFee ?? null,
        setupFee: null,
        isBase: mod.isBase,
        isActive: true,
        sortOrder: mod.sortOrder,
      });
      seeded++;
    } else {
      skipped++;
    }
  }

  console.log(`  ✅ Service modules: ${seeded} seeded, ${skipped} already exist`);
}
