// server/db/seedCompliance.ts — Seed compliance templates for all jurisdictions
// 30 templates across CA Federal, AB, ON, QC, BC, US Federal, FL, TX, CA_STATE

import { db } from "../db";
import { complianceTemplates } from "@shared/schema";
import { eq, and } from "drizzle-orm";

const TEMPLATES = [
  // ── CANADA FEDERAL ────────────────────────────────────────────────────────
  {
    country: "CA",
    jurisdiction: "FEDERAL",
    regulatorName: "Competition Bureau",
    regulatorFullName: "Competition Bureau Canada",
    category: "advertising" as const,
    requirementName: "Competition Act — Truthful Advertising",
    requirementDescription: "All advertised prices, features, and claims must be truthful and not misleading under the Competition Act.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "FEDERAL",
    regulatorName: "OPC",
    regulatorFullName: "Office of the Privacy Commissioner of Canada",
    category: "privacy" as const,
    requirementName: "PIPEDA — Privacy Policy on File",
    requirementDescription: "A written privacy policy must be maintained and made available to customers as required by PIPEDA.",
    documentRequired: "Privacy Policy",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "FEDERAL",
    regulatorName: "OPC",
    regulatorFullName: "Office of the Privacy Commissioner of Canada",
    category: "privacy" as const,
    requirementName: "PIPEDA — Customer Data Consent",
    requirementDescription: "Customer consent must be obtained before collecting, using, or disclosing personal information.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "FEDERAL",
    regulatorName: "Consumer Protection",
    regulatorFullName: "Federal Consumer Protection (Canada)",
    category: "consumer_protection" as const,
    requirementName: "Cooling-Off Period Documentation",
    requirementDescription: "Documentation of cooling-off period rights must be provided to customers where applicable under federal consumer protection guidelines.",
    documentRequired: "Cooling-Off Period Notice",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "medium" as const,
  },

  // ── ALBERTA (AMVIC) ───────────────────────────────────────────────────────
  {
    country: "CA",
    jurisdiction: "AB",
    regulatorName: "AMVIC",
    regulatorFullName: "Alberta Motor Vehicle Industry Council",
    category: "dealer_licensing" as const,
    requirementName: "AMVIC Dealer Licence — Current",
    requirementDescription: "The dealership must maintain a current AMVIC dealer licence at all times.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "AB",
    regulatorName: "AMVIC",
    regulatorFullName: "Alberta Motor Vehicle Industry Council",
    category: "advertising" as const,
    requirementName: "All-In Pricing on Advertised Vehicles",
    requirementDescription: "All advertised prices must be all-inclusive (no hidden fees) as required by AMVIC advertising standards.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "AB",
    regulatorName: "AMVIC",
    regulatorFullName: "Alberta Motor Vehicle Industry Council",
    category: "disclosure" as const,
    requirementName: "Material Facts Disclosure (Damage / Liens)",
    requirementDescription: "All material facts including damage history, existing liens, and title issues must be disclosed in writing prior to sale.",
    documentRequired: "Material Disclosure Form",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "AB",
    regulatorName: "AMVIC",
    regulatorFullName: "Alberta Motor Vehicle Industry Council",
    category: "disclosure" as const,
    requirementName: "Bill of Sale on File for Every Transaction",
    requirementDescription: "A signed Bill of Sale must be on file for every completed vehicle transaction.",
    documentRequired: "Bill of Sale",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "AB",
    regulatorName: "AMVIC",
    regulatorFullName: "Alberta Motor Vehicle Industry Council",
    category: "consumer_protection" as const,
    requirementName: "Customer Consent Forms Signed",
    requirementDescription: "Customer consent forms must be signed acknowledging rights under AMVIC consumer protection provisions.",
    documentRequired: "Customer Consent Form",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },

  // ── ONTARIO (OMVIC) ───────────────────────────────────────────────────────
  {
    country: "CA",
    jurisdiction: "ON",
    regulatorName: "OMVIC",
    regulatorFullName: "Ontario Motor Vehicle Industry Council",
    category: "dealer_licensing" as const,
    requirementName: "OMVIC Registered Dealer Status — Current",
    requirementDescription: "The dealership must maintain current OMVIC registered dealer status under the Motor Vehicle Dealers Act.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "ON",
    regulatorName: "OMVIC",
    regulatorFullName: "Ontario Motor Vehicle Industry Council",
    category: "advertising" as const,
    requirementName: "All-In Pricing Compliance (MVDA)",
    requirementDescription: "All advertised prices must comply with OMVIC all-in pricing requirements under the Motor Vehicle Dealers Act.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "ON",
    regulatorName: "OMVIC",
    regulatorFullName: "Ontario Motor Vehicle Industry Council",
    category: "disclosure" as const,
    requirementName: "MVDA Disclosure Requirements on File",
    requirementDescription: "All MVDA required disclosure documents must be completed and on file for each vehicle transaction.",
    documentRequired: "MVDA Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "ON",
    regulatorName: "OMVIC",
    regulatorFullName: "Ontario Motor Vehicle Industry Council",
    category: "financial" as const,
    requirementName: "Trust Account for Deposits Maintained",
    requirementDescription: "Customer deposits must be held in a separate trust account as required by OMVIC regulations.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },

  // ── QUEBEC (SAAQ/OPC) ─────────────────────────────────────────────────────
  {
    country: "CA",
    jurisdiction: "QC",
    regulatorName: "SAAQ/OPC",
    regulatorFullName: "Société de l'assurance automobile du Québec / Office de la protection du consommateur",
    category: "safety" as const,
    requirementName: "Vehicle Inspection Certificate for Used Vehicles",
    requirementDescription: "A valid vehicle inspection certificate (attestation de conformité) is required for all used vehicle sales in Quebec.",
    documentRequired: "Inspection Certificate",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "QC",
    regulatorName: "SAAQ/OPC",
    regulatorFullName: "Société de l'assurance automobile du Québec / Office de la protection du consommateur",
    category: "consumer_protection" as const,
    requirementName: "Consumer Protection Disclosures in French",
    requirementDescription: "All consumer protection disclosures, contracts, and notices must be provided in French as required by the Charter of the French Language.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "CA",
    jurisdiction: "QC",
    regulatorName: "SAAQ/OPC",
    regulatorFullName: "Société de l'assurance automobile du Québec / Office de la protection du consommateur",
    category: "warranty" as const,
    requirementName: "Warranty Disclosures per OPC Guidelines",
    requirementDescription: "Warranty disclosures must comply with OPC guidelines and be provided in writing to customers.",
    documentRequired: "OPC Warranty Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },

  // ── BRITISH COLUMBIA (VSA) ────────────────────────────────────────────────
  {
    country: "CA",
    jurisdiction: "BC",
    regulatorName: "VSA",
    regulatorFullName: "Vehicle Sales Authority of British Columbia",
    category: "dealer_licensing" as const,
    requirementName: "VSA Dealer Licence — Current",
    requirementDescription: "The dealership must hold and maintain a current VSA dealer licence under the Motor Dealer Act.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "CA",
    jurisdiction: "BC",
    regulatorName: "VSA",
    regulatorFullName: "Vehicle Sales Authority of British Columbia",
    category: "disclosure" as const,
    requirementName: "Material Latent Defects Disclosed",
    requirementDescription: "All known material latent defects must be disclosed in writing prior to the sale of any vehicle.",
    documentRequired: "Defect Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },

  // ── US FEDERAL ────────────────────────────────────────────────────────────
  {
    country: "US",
    jurisdiction: "FEDERAL",
    regulatorName: "FTC",
    regulatorFullName: "Federal Trade Commission",
    category: "disclosure" as const,
    requirementName: "FTC Used Car Rule — Buyers Guide on Every Used Vehicle",
    requirementDescription: "A completed FTC Buyers Guide must be displayed on every used vehicle offered for sale, as required by the Used Motor Vehicle Trade Regulation Rule.",
    documentRequired: "FTC Buyers Guide",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "US",
    jurisdiction: "FEDERAL",
    regulatorName: "FTC",
    regulatorFullName: "Federal Trade Commission",
    category: "warranty" as const,
    requirementName: "Magnuson-Moss Warranty Act — Warranty Terms Clearly Stated",
    requirementDescription: "All written warranties must clearly state terms and conditions as required by the Magnuson-Moss Warranty Act.",
    documentRequired: "Warranty Terms Document",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "US",
    jurisdiction: "FEDERAL",
    regulatorName: "CFPB",
    regulatorFullName: "Consumer Financial Protection Bureau",
    category: "financial" as const,
    requirementName: "Truth in Lending Act (TILA) — Financing Disclosure",
    requirementDescription: "TILA disclosures including APR, finance charge, and payment schedule must be provided for all financed transactions.",
    documentRequired: "TILA Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "US",
    jurisdiction: "FEDERAL",
    regulatorName: "FTC/CFPB",
    regulatorFullName: "Federal Trade Commission / Consumer Financial Protection Bureau",
    category: "privacy" as const,
    requirementName: "GLBA — Financial Privacy Notice",
    requirementDescription: "A Gramm-Leach-Bliley Act privacy notice must be provided to customers when their financial information is collected.",
    documentRequired: "Privacy Notice",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },

  // ── FLORIDA (FLHSMV) ──────────────────────────────────────────────────────
  {
    country: "US",
    jurisdiction: "FL",
    regulatorName: "FLHSMV",
    regulatorFullName: "Florida Department of Highway Safety and Motor Vehicles",
    category: "safety" as const,
    requirementName: "Temporary Tag Compliance",
    requirementDescription: "All sold vehicles must be issued a valid temporary tag in compliance with FLHSMV regulations.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "US",
    jurisdiction: "FL",
    regulatorName: "FLHSMV",
    regulatorFullName: "Florida Department of Highway Safety and Motor Vehicles",
    category: "disclosure" as const,
    requirementName: "Title Transfer Within 30 Days of Sale",
    requirementDescription: "Vehicle title must be transferred to the buyer within 30 days of sale as required by Florida law.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "US",
    jurisdiction: "FL",
    regulatorName: "FLHSMV",
    regulatorFullName: "Florida Department of Highway Safety and Motor Vehicles",
    category: "dealer_licensing" as const,
    requirementName: "Dealer Surety Bond — Current",
    requirementDescription: "The dealership must maintain a current surety bond as required by Florida dealer licensing regulations.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },

  // ── TEXAS (TxDMV) ─────────────────────────────────────────────────────────
  {
    country: "US",
    jurisdiction: "TX",
    regulatorName: "TxDMV",
    regulatorFullName: "Texas Department of Motor Vehicles",
    category: "dealer_licensing" as const,
    requirementName: "GDN (General Distinguishing Number) — Current",
    requirementDescription: "The dealership must hold a current General Distinguishing Number (GDN) issued by TxDMV.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "US",
    jurisdiction: "TX",
    regulatorName: "TxDMV",
    regulatorFullName: "Texas Department of Motor Vehicles",
    category: "disclosure" as const,
    requirementName: "Tax, Title, License Disclosure on File",
    requirementDescription: "TTL disclosures must be provided to customers and documented on file for all Texas vehicle transactions.",
    documentRequired: "TTL Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },

  // ── CALIFORNIA STATE (DMV/BAR) ────────────────────────────────────────────
  {
    country: "US",
    jurisdiction: "CA_STATE",
    regulatorName: "DMV/BAR",
    regulatorFullName: "California Department of Motor Vehicles / Bureau of Automotive Repair",
    category: "dealer_licensing" as const,
    requirementName: "California DMV Dealer Licence — Current",
    requirementDescription: "The dealership must maintain a current dealer licence issued by the California Department of Motor Vehicles.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "critical" as const,
  },
  {
    country: "US",
    jurisdiction: "CA_STATE",
    regulatorName: "DMV/BAR",
    regulatorFullName: "California Department of Motor Vehicles / Bureau of Automotive Repair",
    category: "dealer_licensing" as const,
    requirementName: "BAR Registration for Repairs",
    requirementDescription: "Any repair work performed at the dealership requires current Bureau of Automotive Repair (BAR) registration.",
    documentRequired: null,
    verificationMethod: "manual_review" as const,
    verificationField: null,
    severity: "high" as const,
  },
  {
    country: "US",
    jurisdiction: "CA_STATE",
    regulatorName: "DMV/BAR",
    regulatorFullName: "California Department of Motor Vehicles / Bureau of Automotive Repair",
    category: "consumer_protection" as const,
    requirementName: "Lemon Law Disclosure",
    requirementDescription: "California lemon law disclosures must be provided to customers purchasing vehicles under the Song-Beverly Consumer Warranty Act.",
    documentRequired: "Lemon Law Disclosure",
    verificationMethod: "document_check" as const,
    verificationField: null,
    severity: "high" as const,
  },
];

export async function seedComplianceTemplates() {
  console.log("  🔧 Seeding compliance templates...");
  let seeded = 0;
  let skipped = 0;

  for (const tpl of TEMPLATES) {
    const [existing] = await db
      .select({ id: complianceTemplates.id })
      .from(complianceTemplates)
      .where(
        and(
          eq(complianceTemplates.jurisdiction, tpl.jurisdiction),
          eq(complianceTemplates.requirementName, tpl.requirementName)
        )
      )
      .limit(1);

    if (!existing) {
      await db.insert(complianceTemplates).values({
        country: tpl.country,
        jurisdiction: tpl.jurisdiction,
        regulatorName: tpl.regulatorName,
        regulatorFullName: tpl.regulatorFullName,
        category: tpl.category,
        requirementName: tpl.requirementName,
        requirementDescription: tpl.requirementDescription,
        documentRequired: tpl.documentRequired ?? null,
        verificationMethod: tpl.verificationMethod,
        verificationField: tpl.verificationField ?? null,
        severity: tpl.severity,
        isActive: true,
      });
      seeded++;
    } else {
      skipped++;
    }
  }

  const byJurisdiction: Record<string, number> = {};
  for (const tpl of TEMPLATES) {
    byJurisdiction[tpl.jurisdiction] = (byJurisdiction[tpl.jurisdiction] || 0) + 1;
  }
  const jurisdictionSummary = Object.entries(byJurisdiction)
    .map(([j, n]) => `${j}:${n}`)
    .join(", ");
  console.log(`  ✅ Compliance templates: ${seeded} seeded, ${skipped} already exist (${jurisdictionSummary})`);
}
